name: "Jira Integration: Create Task from Issue"

on:
  issues:
    types: [opened]

jobs:
  create-jira-task:
    name: Create Jira Task
    runs-on: ubuntu-latest
    
    steps:
      - name: Extract issue type from labels
        id: extract-type
        run: |
          # Extract issue type from GitHub labels
          ISSUE_TYPE="Task"  # Default type
          LABELS="${{ join(github.event.issue.labels.*.name, ',') }}"
          
          if [[ "$LABELS" == *"bug"* ]] || [[ "$LABELS" == *"Bug"* ]]; then
            ISSUE_TYPE="Bug"
          elif [[ "$LABELS" == *"feature"* ]] || [[ "$LABELS" == *"Feature"* ]] || [[ "$LABELS" == *"enhancement"* ]]; then
            ISSUE_TYPE="Story"
          elif [[ "$LABELS" == *"task"* ]] || [[ "$LABELS" == *"Task"* ]]; then
            ISSUE_TYPE="Task"
          fi
          
          echo "issue_type=$ISSUE_TYPE" >> $GITHUB_OUTPUT
          echo "labels=$LABELS" >> $GITHUB_OUTPUT

      - name: Create Jira Task
        uses: atlassian/gajira-create@v3
        with:
          project: ${{ secrets.JIRA_PROJECT_KEY }}
          issuetype: ${{ steps.extract-type.outputs.issue_type }}
          summary: "${{ github.event.issue.title }}"
          description: |
            *GitHub Issue created by:* ${{ github.event.issue.user.login }}
            *Repository:* ${{ github.repository }}
            *Issue URL:* ${{ github.event.issue.html_url }}
            *Labels:* ${{ steps.extract-type.outputs.labels }}
            
            ---
            
            ${{ github.event.issue.body }}
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Add comment to GitHub issue
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `🎫 **Jira Task Created**
            
            A corresponding task has been automatically created in Jira for this issue.
            
            - **Issue Type:** ${{ steps.extract-type.outputs.issue_type }}
            - **Project:** ${{ secrets.JIRA_PROJECT_KEY }}
            
            The Jira task includes:
            - Issue title and description
            - Author information (${{ github.event.issue.user.login }})
            - Repository name and link
            - Issue labels and type classification`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });